import json
import re

from typing import Any

from src.config.settings import EVALUATION_PASS_THRESHOLD
from src.llm.llm_factory import get_chat_model
from src.schemas.evaluation import EvaluationResult

EVALUATOR_SYSTEM_INSTRUCTIONS = """
You are a strict enterprise AI quality evaluator.

Your task is to evaluate the quality of a support answer generated by a specialized RAG agent.

You must evaluate the answer using only:
- the original user question
- the detected department
- the generated answer
- the retrieved source metadata and source previews

Do not answer the user question.
Do not rewrite the answer.
Do not invent missing documentation.
Only evaluate quality.

Scoring dimensions from 1 to 10:

1. relevance:
Does the answer directly address the user's question?

2. completeness:
Does the answer include the necessary steps, required information, exceptions, and escalation guidance when relevant?

3. accuracy:
Does the answer avoid unsupported claims, contradictions, or invented procedures?

4. groundedness:
Is the answer supported by the retrieved sources?

5. clarity:
Is the answer professional, clear, concise, and operationally useful?

Overall score:
Average the five dimensions and return a float from 1 to 10.

Passed:
true if overall_score is greater than or equal to the configured pass threshold.
false otherwise.

Risk level:
- low: score >= 8
- medium: score >= 6 and < 8
- high: score < 6

Return only valid JSON.
"""

def strip_json_code_fence(raw_text: str) -> str:
    cleaned = raw_text.strip()

    cleaned = re.sub(
        r"^```json\s*",
        "",
        cleaned,
        flags=re.IGNORECASE,
    )

    cleaned = re.sub(
        r"^```\s*",
        "",
        cleaned,
    )

    cleaned = re.sub(
        r"\s*```$",
        "",
        cleaned,
    )

    return cleaned.strip()

def build_evaluation_prompt(final_response: dict[str, Any]) -> str:
    compact_sources = []

    for source in final_response.get("sources", []):
        compact_sources.append(
            {
                "chunk_id": source.get("chunk_id"),
                "department": source.get("department"),
                "source_file": source.get("source_file"),
                "score": source.get("score"),
                "content_preview": source.get("content_preview", "")[:700],
            }
        )

    evaluation_payload = {
        "user_question": final_response.get("user_question"),
        "detected_department": final_response.get("detected_department"),
        "routing_confidence": final_response.get("routing_confidence"),
        "routing_reason": final_response.get("routing_reason"),
        "matched_keywords": final_response.get("matched_keywords", []),
        "agent_name": final_response.get("agent_name"),
        "answer": final_response.get("answer"),
        "sources": compact_sources,
        "pass_threshold": EVALUATION_PASS_THRESHOLD,
    }

    return f"""
    {EVALUATOR_SYSTEM_INSTRUCTIONS}
    {json.dumps(evaluation_payload, indent=2)}

    Return JSON with exactly this structure:

    {{
    "relevance": 1,
    "completeness": 1,
    "accuracy": 1,
    "groundedness": 1,
    "clarity": 1,
    "overall_score": 1.0,
    "passed": false,
    "risk_level": "high",
    "reason": "...",
    "improvement_suggestions": ["..."]
    }}
    """.strip()

def calculate_overall_score(parsed: dict[str, Any]) -> float:
    dimensions = [
        int(parsed.get("relevance", 1)),
        int(parsed.get("completeness", 1)),
        int(parsed.get("accuracy", 1)),
        int(parsed.get("groundedness", 1)),
        int(parsed.get("clarity", 1)),
    ]

    return round(sum(dimensions) / len(dimensions), 2)


def infer_risk_level(overall_score: float) -> str:
    if overall_score >= 8:
        return "low"

    if overall_score >= 6:
        return "medium"

    return "high"

def fallback_evaluation(final_response: dict[str, Any]) -> EvaluationResult:
    answer = final_response.get("answer") or ""
    sources = final_response.get("sources", [])
    department = final_response.get("detected_department")

    if not answer.strip():
        return EvaluationResult(
            relevance=1,
            completeness=1,
            accuracy=1,
            groundedness=1,
            clarity=1,
            overall_score=1.0,
            passed=False,
            risk_level="high",
            reason="The response is empty.",
            improvement_suggestions=[
                "Generate a complete answer before returning it to the user."
            ],
        )

    if department == "fallback":
        return EvaluationResult(
            relevance=9,
            completeness=8,
            accuracy=9,
            groundedness=9,
            clarity=9,
            overall_score=8.8,
            passed=True,
            risk_level="low",
            reason=(
                "The response correctly avoided answering an unsupported "
                "out-of-domain question and routed the user to provide more details."
            ),
            improvement_suggestions=[],
        )

    if not sources:
        return EvaluationResult(
            relevance=5,
            completeness=4,
            accuracy=4,
            groundedness=1,
            clarity=7,
            overall_score=4.2,
            passed=False,
            risk_level="high",
            reason="The response has no retrieved sources for a domain-specific answer.",
            improvement_suggestions=[
                "Retrieve domain documentation before generating the answer.",
                "Include source metadata with the response.",
            ],
        )

    if len(answer.split()) < 20:
        return EvaluationResult(
            relevance=5,
            completeness=3,
            accuracy=5,
            groundedness=5,
            clarity=6,
            overall_score=4.8,
            passed=False,
            risk_level="high",
            reason="The response is too short to be operationally useful.",
            improvement_suggestions=[
                "Include required steps, conditions, and escalation guidance."
            ],
        )

    return EvaluationResult(
        relevance=7,
        completeness=7,
        accuracy=7,
        groundedness=7,
        clarity=7,
        overall_score=7.0,
        passed=True,
        risk_level="medium",
        reason="Fallback evaluator assigned a neutral passing score.",
        improvement_suggestions=[
            "Review the answer with the LLM evaluator when available."
        ],
    )

def evaluate_response_quality(final_response: dict[str, Any]) -> EvaluationResult:
    prompt = build_evaluation_prompt(final_response)

    try:
        model = get_chat_model(temperature=0)
        model_response = model.invoke(prompt)

        raw_content = strip_json_code_fence(str(model_response.content))
        parsed = json.loads(raw_content)

        overall_score = calculate_overall_score(parsed)
        passed = overall_score >= EVALUATION_PASS_THRESHOLD
        risk_level = infer_risk_level(overall_score)

        return EvaluationResult(
            relevance=int(parsed["relevance"]),
            completeness=int(parsed["completeness"]),
            accuracy=int(parsed["accuracy"]),
            groundedness=int(parsed["groundedness"]),
            clarity=int(parsed["clarity"]),
            overall_score=overall_score,
            passed=passed,
            risk_level=risk_level,
            reason=str(parsed.get("reason", "")),
            improvement_suggestions=list(
                parsed.get("improvement_suggestions", [])
            ),
        )

    except Exception:
        return fallback_evaluation(final_response)